"""create all tables + indexes

Revision ID: 1b950deef6f2
Revises: 5e7a2618bd07
Create Date: 2025-05-22 22:48:00.967807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b950deef6f2'
down_revision: Union[str, None] = '5e7a2618bd07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.drop_constraint(op.f('event_exceptions_event_id_fkey'), 'event_exceptions', type_='foreignkey')
    op.create_foreign_key(None, 'event_exceptions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ux_event_permissions_event_user'), table_name='event_permissions')
    op.create_unique_constraint('ux_event_permissions_event_user', 'event_permissions', ['event_id', 'user_id'])
    op.drop_index(op.f('ux_event_versions_event_version'), table_name='event_versions')
    op.create_unique_constraint('ux_event_versions_event_version', 'event_versions', ['event_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_event_versions_event_version', 'event_versions', type_='unique')
    op.create_index(op.f('ux_event_versions_event_version'), 'event_versions', ['event_id', 'version_number'], unique=True)
    op.drop_constraint('ux_event_permissions_event_user', 'event_permissions', type_='unique')
    op.create_index(op.f('ux_event_permissions_event_user'), 'event_permissions', ['event_id', 'user_id'], unique=True)
    op.drop_constraint(None, 'event_exceptions', type_='foreignkey')
    op.create_foreign_key(op.f('event_exceptions_event_id_fkey'), 'event_exceptions', 'events', ['event_id'], ['id'])
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    # ### end Alembic commands ###
