"""add version_number and updated_at to events

Revision ID: 5608a0417b53
Revises: 07b6cf23bd15
Create Date: 2025-05-22 17:18:11.825902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5608a0417b53'
down_revision: Union[str, None] = '07b6cf23bd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('version_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('events', 'start_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'end_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_events_creator_id'), table_name='events')
    op.drop_index(op.f('ix_events_end_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_start_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_constraint(op.f('events_creator_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['creator_id'], ['id'])
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_creator_id_fkey'), 'events', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_index(op.f('ix_events_start_datetime'), 'events', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_events_end_datetime'), 'events', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_events_creator_id'), 'events', ['creator_id'], unique=False)
    op.alter_column('events', 'end_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'start_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'version_number')
    # ### end Alembic commands ###
