"""add permissions and versioning tables

Revision ID: 6aa1e37d4920
Revises: 0b952a98b16c
Create Date: 2025-05-21 15:21:05.867883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa1e37d4920'
down_revision: Union[str, None] = '0b952a98b16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_permissions_event_id'), 'event_permissions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_permissions_id'), 'event_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_event_permissions_user_id'), 'event_permissions', ['user_id'], unique=False)
    op.create_table('event_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_versions_event_id'), 'event_versions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_versions_id'), 'event_versions', ['id'], unique=False)
    op.create_table('event_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_version_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_version_id'], ['event_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_changes_event_version_id'), 'event_changes', ['event_version_id'], unique=False)
    op.create_index(op.f('ix_event_changes_id'), 'event_changes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_changes_id'), table_name='event_changes')
    op.drop_index(op.f('ix_event_changes_event_version_id'), table_name='event_changes')
    op.drop_table('event_changes')
    op.drop_index(op.f('ix_event_versions_id'), table_name='event_versions')
    op.drop_index(op.f('ix_event_versions_event_id'), table_name='event_versions')
    op.drop_table('event_versions')
    op.drop_index(op.f('ix_event_permissions_user_id'), table_name='event_permissions')
    op.drop_index(op.f('ix_event_permissions_id'), table_name='event_permissions')
    op.drop_index(op.f('ix_event_permissions_event_id'), table_name='event_permissions')
    op.drop_table('event_permissions')
    # ### end Alembic commands ###
